apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer-app
  template:
    metadata:
      labels:
        app: writer-app
    spec:
      containers:
        - name: writer-app
          image: lofmakim/writer-app:v0.1