apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: ClusterIP
  selector:
    app: todo-full
  ports:
    - port: 2345
      name: todo-app
      protocol: TCP
      targetPort: 3000
    - port: 2346
      name: todo-backend
      protocol: TCP
      targetPort: 3002