apiVersion: v1
kind: Service
metadata:
  name: log-ping-svc
spec:
  type: ClusterIP
  selector:
    app: log-ping
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
    - port: 2346
      protocol: TCP
      targetPort: 3001