apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-generator
  namespace: todo-test
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-generator
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              RANDOM_URL=$(curl -s -I https://en.wikipedia.org/wiki/Special:Random | grep -i Location | awk '{print $2}' | tr -d '\r')
              curl -X POST \
                -H "Content-Type: application/json" \
                -d '{"title": "Read '$RANDOM_URL'"}' \
                http://todo-svc:2346/todos
          restartPolicy: OnFailure
