apiVersion: v1
kind: Service
metadata:
  name: ping-svc
  namespace: log-test
spec:
  type: LoadBalancer
  selector:
    app: ping-app
  ports:
    - port: 80
      name: pingpong-app
      protocol: TCP
      targetPort: 3001