apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: lofmakim/log-output:241e0b1a1022796d09b2ba5c9bdb07c84aa76040
          env:
          - name: PORT
            value: "3000"