apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-ping-claim
spec:
  storageClassName: logoutput-pingpong-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi