apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-ping-dep
  namespace: log-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-ping
  template:
    metadata:
      labels:
        app: log-ping
    spec:
      containers:
        - name: log-output
          image: lofmakim/log-output:v3.2
          env:
          - name: PORT
            value: "3000"
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: log-output-config
                key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: '/usr/src/app/config'
        - name: pingpong-app
          image: lofmakim/pingpong-app:v3.2.3
          env:
          - name: PORT
            value: "3001"
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: myuser
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: DB_NAME
            value: mydatabase
      volumes:
        - name: config-volume
          configMap:
            name: log-output-config