apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-v0.2
  template:
    metadata:
      labels:
        app: project-v0.2
    spec:
      containers:
        - name: project-v0.2
          image: lofmakim/project-v0.2:latest